sched: core: fix build after f764781c1b02005f986d7d6411a9960c0eb62f1d
Due to changes made in 06f9406a976dc9fb3415b0a934949e1f1468d7a4
we were greeted by some very annoying warns after picking f764781c1b02005f986d7d6411a9960c0eb62f1d:

../kernel/sched/core.c:2145:46: error: no member named 'cpus_allowed' in 'struct task_struct'
        *cpumask_bits(old_mask) = *cpumask_bits(&p->cpus_allowed);
                                                 ~  ^
../include/linux/cpumask.h:25:31: note: expanded from macro 'cpumask_bits'
                              ^~~~~
../kernel/sched/core.c:2166:24: error: no member named 'cpus_allowed' in 'struct task_struct'
        if (*cpumask_bits(&p->cpus_allowed) == *cpumask_bits(dest)) {
                           ~  ^
../include/linux/cpumask.h:25:31: note: expanded from macro 'cpumask_bits'
                              ^~~~~
2 errors generated.
make[3]: *** [../scripts/Makefile.build:338: kernel/sched/core.o] Error 1
make[2]: *** [../scripts/Makefile.build:642: kernel/sched] Error 2
make[1]: *** [/home/nucleus/Desktop/Atom-X-Projekt/Kernel-4.19/Makefile:1196: kernel] Error 2
make[1]: *** Waiting for unfinished jobs....

Fixes: f764781c1b02005f986d7d6411a9960c0eb62f1d (sched: Add API to migrate the current process to a given cpumask)
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>